# Disk layout for kastner-ml (declarative, via disko).
#
# GOTCHA — disko is DESTRUCTIVE and not idempotent. `disko --mode disko` (or
# nixos-anywhere) wipes and repartitions EVERY device listed below on every run.
# Run it once at install, then only ever `--mode mount` on later boots. The live
# Ubuntu root (btrfs-over-bcache) is destroyed by this — confirm the
# e4e-nas/2026_kastner_ml_dump backup is current first (docs/kastner-ml-onboarding.md).
#
# GOTCHA — device paths are /dev/disk/by-id/* on purpose (matches boot.zfs.devNodes);
# kernel sdX/nvmeXn1 names reshuffle. Verified on-box 2026-06-08 via `ls -l
# /dev/disk/by-id/`.
#
# ============================================================================
# WHY THIS LAYOUT — three heterogeneous, single disks (no redundancy possible)
# ----------------------------------------------------------------------------
# Unlike waiter (4× NVMe RAIDZ1 + 2× HDD), kastner-ml has exactly ONE of each disk
# kind, so no vdev can be redundant. The roles still follow waiter's split:
#
#   * rpool      = the 2 TB SATA SSD (Crucial MX500). OS + nix + persist + docker +
#                  /local. Single-disk: the OS is flake-reproducible and /persist is
#                  re-derivable (re-join AD, regen host keys), so no redundancy is
#                  acceptable. Impermanence rolls / back to rpool/root@blank.
#   * scratchpool = the 8 TB HDD (data) + the 118 GB Intel Optane 800P split into a
#                  `special` (metadata-only) partition + a `cache` (L2ARC) partition.
#                  ZFS serves hot reads from RAM (ARC) -> Optane (L2ARC) -> HDD, and
#                  keeps ALL metadata on Optane so listings over 8 TB stay fast. NO
#                  redundancy anywhere (single HDD, single Optane special) — losing
#                  either loses the pool. Accepted: scratch is regenerable, smartd
#                  warns early, and the group scratch areas are E4E project space (the
#                  durable copy belongs on e4e-nas).
#
# MOUNTPOINT POLICY — boot/OS datasets use options.mountpoint = "legacy" so NixOS
# fileSystems (generated by disko) is the single authority for what mounts where.
# The /local and /scratch-* datasets have NO top-level `mountpoint` (disko emits no
# fileSystems entry) — krg.localCache / krg.scratch own those mounts.
{...}: let
  espSize = "2G"; # vfat ESP; 2G so GRUB copyKernels + configurationLimit fit (ZFS initrds are chunky)

  # Optane 800P is 110.3 GiB usable. special 48G + cache 56G = 104 GiB, leaving
  # ~6 GiB UNPARTITIONED as SSD overprovisioning (L2ARC write endurance). special is
  # generous: metadata for ~7 TiB at recordsize=1M is well under 48 GiB, and ZFS
  # spills metadata to the HDD data vdev gracefully if it ever fills.
  specialSize = "48G";
  cacheSize = "56G";

  byPartlabel = l: "/dev/disk/by-partlabel/${l}";

  # Inherited-by-children pool root props (identical posture to waiter).
  zfsRootProps = {
    mountpoint = "none";
    compression = "zstd";
    atime = "off";
    xattr = "sa";
    acltype = "posixacl";
    "com.sun:auto-snapshot" = "false"; # default OFF; datasets opt in below
  };
in {
  disko.devices = {
    disk = {
      # ---- 2 TB SATA SSD: ESP + rpool (OS pool) ----
      ssd = {
        type = "disk";
        device = "/dev/disk/by-id/ata-CT2000MX500SSD1_1817E13973A1"; # Crucial MX500 2TB
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              size = espSize;
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = ["umask=0077" "nofail"];
              };
            };
            rpool = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "rpool";
              };
            };
          };
        };
      };

      # ---- 118 GB Intel Optane 800P: scratchpool special (metadata) + cache (L2ARC) ----
      optane = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-INTEL_SSDPEK1W120GA_PHBT8070009L128R"; # Optane 800P 118GB
        content = {
          type = "gpt";
          partitions = {
            special = {
              size = specialSize;
              label = "kml-special";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
            cache = {
              size = cacheSize;
              label = "kml-cache";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
            # remainder left unpartitioned (overprovisioning)
          };
        };
      };

      # ---- 8 TB HDD: whole-disk -> scratchpool data vdev ----
      hdd = {
        type = "disk";
        device = "/dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_R6G808WY"; # WD Red 8TB
        content = {
          type = "gpt";
          partitions = {
            zfs = {
              size = "100%";
              label = "kml-hdd";
              content = {
                type = "zfs";
                pool = "scratchpool";
              };
            };
          };
        };
      };
    };

    zpool = {
      # ===================== rpool (OS, single SSD, no redundancy) =============
      rpool = {
        type = "zpool";
        mode = ""; # single vdev (one device) — no raidz/mirror
        options = {
          ashift = "12";
          autotrim = "on"; # SSD pool
        };
        rootFsOptions = zfsRootProps;

        datasets = {
          root = {
            type = "zfs_fs";
            mountpoint = "/";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "false"; # rolled back, never snapshotted
            # @blank captured empty at install; impermanence rolls back to it each boot.
            # (modules/impermanence.nix reseeds /usr/bin/env in initrd so an empty root
            # boots under systemd 258 — see that module + krg.impermanence below.)
            postCreateHook = ''
              zfs list -t snapshot -H -o name | grep -qx 'rpool/root@blank' \
                || zfs snapshot rpool/root@blank
            '';
          };

          nix = {
            type = "zfs_fs";
            mountpoint = "/nix";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "false"; # store is reproducible
          };

          persist = {
            type = "zfs_fs";
            mountpoint = "/persist";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "true";
          };

          # Docker on its own dataset (image/layer churn off /persist's snapshots; stays
          # durable independent of the impermanence rollback — see modules/impermanence.nix).
          docker = {
            type = "zfs_fs";
            mountpoint = "/var/lib/docker";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "false";
          };

          # Node-local per-user cache (krg.localCache): IDE servers + cache class off the
          # NFS /home. No top-level mountpoint -> krg.localCache owns the legacy /local
          # mount. quota 500G (the 2 TB SSD also holds nix store + CUDA Docker images).
          local = {
            type = "zfs_fs";
            options = {
              mountpoint = "legacy";
              quota = "500G";
              "com.sun:auto-snapshot" = "false";
            };
          };
        };
      };

      # ===================== scratchpool (HDD data + Optane special/cache) =====
      # Vdev ROLES come from mode.topology — content.pool only says "belongs to
      # scratchpool". NO redundancy anywhere (single HDD data, single Optane special):
      # a failure of either loses the pool. Accepted (regenerable; smartd warns).
      scratchpool = {
        type = "zpool";
        mode = {
          topology = {
            type = "topology";
            vdev = [
              {members = [(byPartlabel "kml-hdd")];} # DATA: where the bytes live
            ];
            special = [
              {members = [(byPartlabel "kml-special")];} # metadata-only (Optane)
            ];
            cache = [
              (byPartlabel "kml-cache") # L2ARC (Optane); losing it is harmless
            ];
          };
        };
        options.ashift = "12";
        rootFsOptions = zfsRootProps;

        datasets = let
          # Group-collaborative scratch (E4E project groups). mountpoint=legacy ->
          # krg.scratch owns the /scratch/<group> mount and applies 3770 (setgid+sticky,
          # group-writable) + group ownership. recordsize 1M for bulk data; relatime so a
          # future overflow mover can sort by last-access. Snapshots OFF (scratch
          # semantics — the durable copy belongs on e4e-nas).
          scratchGroup = {
            type = "zfs_fs";
            options = {
              mountpoint = "legacy";
              recordsize = "1M";
              atime = "on";
              relatime = "on";
              "com.sun:auto-snapshot" = "false";
            };
          };
        in {
          scratch-fishsense = scratchGroup;
          scratch-aid = scratchGroup;
          # Shared Hugging Face model cache (HF_HOME points here for the group). Pure
          # cache, so the same scratch-semantics props apply.
          scratch-huggingface = scratchGroup;
        };
      };
    };
  };
}
